care_app/urls.py
from django.urls import path
from .import views

app_name = "care"

urlpatterns = [
    path('', views.home, name="home"), 
    path('doctor/',views.doctor, name='doctor-page'),
    path('add-doctor/',views.add_doctor,name='add-doctor'),
    path('update_doctor/<int:pk>/',views.update_doctor,name='update_doctor'), 
    path('delete_doctor/<int:pk>/',views.delete_doctor,name='delete_doctor'),

    path('patients/',views.patients,name='patients-page'),
    path('add_patients/',views.add_patients,name='add-patients'),
    path('update_patients/<int:pk>/',views.update_patients,name='update-patient'),
    path('delete_patient/<int:pk>/',views.delete_patients,name='delete-patient'),
    path('doctor_profile/<int:pk>/',views.doctor_profile,name='doctor-profile'),

    path('appointment/',views.appointment,name='appointment-page'),
    path('add_appointment/',views.add_appointment,name='add-appointment'),
    path('update_appointment/<int:pk>/',views.update_appointment,name='update-appointment'),
    path('delete_appointment/<int:pk>/',views.delete_appointment,name='delete-appointment'),

    path('schedule/',views.schedule,name='schedule-page'),
    path('add_schedule/',views.add_schedule,name='add-schedule'),
    path('update_schedule/<int:pk>/',views.update_schedule,name='update-schedule'),
    path('delete_schedule/<int:pk>/',views.delete_schedule,name='delete-schedule'),

    path('department/',views.department,name='department-page'),
]

health_care/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('care_app.urls')) 
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_ROOT)

templates/main/m.html
<form>
    {% csrf_token %}
    <div id="delete_doctor" class="modal fade delete-modal" role="dialog">
        
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body text-center"> 
                    <img src="{{delete.image.url}}" alt="" width="50" height="46"> 
                    <h3>Are you sure you want to delete doctor <a href="" class="">{{delete.first_name}} {{delete.second_name}}</a>?</h3>
                    <div class="m-t-20"> <a href="{% url 'care:doctor-page' %}" class="btn btn-white" data-dismiss="modal">Close</a>
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>